# .github/workflows/build.yml
name: build

on:
  pull_request:
  push:
    tags:
      - v[0-9]+.*

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set ENV
        run: |
          echo "KRB_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.ALIYUNACR_REGISTRY }}
          username: ${{ vars.ALIYUNACR_USERNAME }}
          password: ${{ secrets.ALIYUNACR_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push krb-controller
        uses: docker/build-push-action@v6
        with:
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          build-args: |
            KRB_APPNAME=krb-controller
          tags: |
            registry.cn-hangzhou.aliyuncs.com/ketches/krb-controller:${{ env.KRB_VERSION }}
            registry.cn-hangzhou.aliyuncs.com/ketches/krb-controller:latest
            ketches/krb-controller:${{ env.KRB_VERSION }}
            ketches/krb-controller:latest
      
      - name: Build and push krb-webhook
        uses: docker/build-push-action@v6
        with:
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          build-args: |
            KRB_APPNAME=krb-webhook
          tags: |
            registry.cn-hangzhou.aliyuncs.com/ketches/krb-webhook:${{ env.KRB_VERSION }}
            registry.cn-hangzhou.aliyuncs.com/ketches/krb-webhook:latest
            ketches/krb-webhook:${{ env.KRB_VERSION }}
            ketches/krb-webhook:latest